version: "3.9"

services:
  frontend:
    build:
      context: ./front/frontend
    ports:
      - "3000:80"
    networks:
      - app-network

  backend:
    build:
      context: ./back
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: mysql://root:@database:3306/symfony
    networks:
      - app-network
    depends_on:
      - database

  database:
    image: mariadb:10.11
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: symfony
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:

volumes:
  db_data:
